/* Journal: Active Batches & Compounding Log (Append-Only) */

window.JournalActive = (() => {
  async function render(root) {
    // Note: We use the existing 'batches' table generated by Inventory, 
    // but here we manage the GMP/Lab side of it.
    const allBatches = await DB.getAll('batches');
    const formulas = await DB.getAll('formulas');
    
    // Active batches are those not yet Released, Rejected, or Quarantined
    const active = allBatches.filter(b => !['Released', 'Rejected', 'Quarantined'].includes(b.status));

    root.appendChild(el('div', { class: 'muted-note mb-16', style: 'border-left-color:var(--sage)' }, 
      'Welcome to the GMP Production Journal. Entries made here (Compounding, Maceration checks, QC) are permanently logged in the audit trail.'));

    if (!active.length) {
      root.appendChild(emptyState('⚖️', 'No active batches currently in production. Start a batch in the Inventory module.'));
      return;
    }

    const listContainer = el('div', { class: 'card-grid' });
    
    for (const b of active.sort((x, y) => (y.date || '').localeCompare(x.date || ''))) {
      const formula = formulas.find(f => f.id === b.formulaId);
      const logs = await DB.getByIndex('compounding_entries', 'batchId', b.id);
      const isCompounded = logs.length > 0;

      const card = el('div', { class: 'card' }, [
        el('div', { class: 'card-head' }, [
          el('div', { class: 'card-title text-mono' }, b.batchNumber),
          el('span', { class: `badge badge-${isCompounded ? 'ok' : 'pending'}` }, isCompounded ? 'Compounded' : 'Awaiting Weighing')
        ]),
        el('div', { class: 'card-sub' }, [
          el('div', {}, `Formula: ${formula ? formula.name : 'Unknown'}`),
          el('div', {}, `Target: ${fmtNum(b.quantityProduced, 2)} ${b.unit || 'ml'}`),
        ]),
        el('div', { class: 'card-actions mt-12' }, [
          isCompounded 
            ? el('button', { class: 'btn-secondary btn-sm btn-block', onclick: () => viewCompoundingLog(b, logs[0]) }, 'View Weighing Log')
            : el('button', { class: 'btn btn-primary btn-sm btn-block', style: 'background:var(--sage)', onclick: () => openCompoundingForm(b, formula) }, '⚖️ Start Compounding')
        ])
      ]);
      listContainer.appendChild(card);
    }
    root.appendChild(listContainer);
  }

  // Record actual weights during compounding (Append-Only)
  async function openCompoundingForm(batch, formula) {
    const materials = await DB.getAll('materials');
    let entries = [];
    
    const form = el('div', { class: 'modal-form' });
    form.appendChild(formSectionHeader(`Compounding: ${batch.batchNumber}`));
    
    form.appendChild(el('div', { class: 'form-row-2' }, [
      field('Ambient Temp (°C)', 'temp', '', false, 'number'),
      field('Ambient Humidity (%)', 'humidity', '', false, 'number')
    ]));
    
    form.appendChild(field('Compounding Vessel', 'vessel', '', true, 'text', 'e.g., 5L Glass Beaker, Stainless Steel Vat'));
    
    form.appendChild(formSectionHeader('Weighing Log'));
    form.appendChild(el('div', { class: 'muted-note mb-8' }, 'Enter the ACTUAL weight measured. Deviations >2% will be flagged automatically.'));

    const tableWrap = el('div', { style: 'overflow-x:auto' });
    const tbody = el('tbody');
    
    const targetIngredients = batch.consumedMaterials || (formula ? formula.ingredients.map(ing => {
      const multiplier = (batch.quantityProduced || 0) / (formula.batchSize || 1);
      return { materialId: ing.materialId, qty: (formula.batchSize || 0) * multiplier * (ing.pct / 100) };
    }) : []);

    targetIngredients.forEach((ing, idx) => {
      const mat = materials.find(m => m.id === ing.materialId);
      const targetQty = ing.qty || 0;
      
      const tr = el('tr', {}, [
        el('td', {}, mat ? mat.name : 'Unknown'),
        el('td', { class: 'num' }, fmtNum(targetQty, 2)),
        el('td', {}, el('input', { 
          type: 'number', step: '0.01', name: `actual_${idx}`, required: 'required',
          placeholder: 'Actual qty',
          class: 'inline-input',
          oninput: (e) => checkDeviation(e.target, targetQty, idx)
        })),
        el('td', { id: `dev_${idx}`, class: 'num font-bold', style: 'width:60px' }, '—')
      ]);
      tbody.appendChild(tr);
      entries.push({ materialId: ing.materialId, targetQty, name: mat?.name });
    });

    tableWrap.appendChild(el('table', { class: 'data-table compact' }, [
      el('thead', {}, el('tr', {}, ['Material', 'Target', 'Actual', 'Dev %'].map(h => el('th', {}, h)))),
      tbody
    ]));
    form.appendChild(tableWrap);
    
    form.appendChild(textareaField('Compounder Notes', 'notes', '', false, 'List any issues, clumps, specific addition order, etc.'));

    function checkDeviation(input, target, idx) {
      const devCell = document.getElementById(`dev_${idx}`);
      const actual = parseFloat(input.value);
      if (isNaN(actual) || target === 0) { devCell.textContent = '—'; devCell.style.color = ''; return; }
      
      const devPct = ((actual - target) / target) * 100;
      devCell.textContent = (devPct > 0 ? '+' : '') + devPct.toFixed(1) + '%';
      
      if (Math.abs(devPct) > 5) devCell.style.color = 'var(--danger)';
      else if (Math.abs(devPct) > 2) devCell.style.color = 'var(--warn)';
      else devCell.style.color = 'var(--success)';
    }

    openModal('Record Compounding', form, async () => {
      const data = formData(form.closest('form'));
      
      const logEntries = entries.map((e, idx) => {
        const actual = parseFloat(data[`actual_${idx}`]) || 0;
        const devPct = e.targetQty ? ((actual - e.targetQty) / e.targetQty) * 100 : 0;
        return { ...e, actualQty: actual, deviationPct: devPct };
      });

      const totalActual = logEntries.reduce((s, e) => s + e.actualQty, 0);

      const logRecord = {
        batchId: batch.id,
        timestamp: nowISO(),
        temp: parseFloat(data.temp) || null,
        humidity: parseFloat(data.humidity) || null,
        vessel: data.vessel.trim(),
        totalActualWeight: totalActual,
        notes: data.notes.trim(),
        weighingData: logEntries
      };

      // Ensure append-only DB method is used
      await DB.append('compounding_entries', logRecord, 'cmp');
      
      batch.status = 'Compounded';
      await DB.put('batches', batch); // State update to main record is fine
      
      toast('Compounding log permanently recorded', 'success');
      render(document.getElementById('journal-body'));
    }, { wide: true, appendOnly: true, submitLabel: 'Lock Record' });
  }

  // --- UPDATED VIEW FUNCTION WITH PRINT SUPPORT ---
  function viewCompoundingLog(batch, log) {
    const content = el('div', { id: 'print-area' }, [
      el('div', { class: 'stat-strip mb-16' }, [
        statBox('Total Target', fmtNum(batch.quantityProduced, 2)),
        statBox('Total Actual', fmtNum(log.totalActualWeight, 2)),
        statBox('Ambient', `${log.temp||'?'}°C / ${log.humidity||'?'}%`),
        statBox('Vessel', log.vessel || '—')
      ]),
      
      el('table', { class: 'data-table compact mb-16' }, [
        el('thead', {}, el('tr', {}, ['Material', 'Target', 'Actual', 'Deviation'].map(h => el('th', {}, h)))),
        el('tbody', {}, (log.weighingData || []).map(w => {
          const devColor = Math.abs(w.deviationPct) > 5 ? 'var(--danger)' : Math.abs(w.deviationPct) > 2 ? 'var(--warn)' : 'var(--success)';
          return el('tr', {}, [
            el('td', {}, w.name || 'Unknown'),
            el('td', { class: 'num' }, fmtNum(w.targetQty, 2)),
            el('td', { class: 'num' }, fmtNum(w.actualQty, 2)),
            el('td', { class: 'num font-bold', style: `color:${devColor}` }, (w.deviationPct > 0 ? '+' : '') + w.deviationPct.toFixed(2) + '%'),
          ]);
        }))
      ]),

      log.notes ? el('div', { class: 'muted-note mb-16' }, `Notes: ${log.notes}`) : null,
      
      el('div', { class: 'detail-meta' }, `Locked Record · Created: ${fmtDateTime(log.timestamp)}`)
    ]);

    // Create the Print Button
    const printBtn = el('button', { 
      class: 'btn-secondary btn-sm', 
      onclick: () => window.print() 
    }, '🖨 Print BMR');

    openModal(`Batch Manufacturing Record: ${batch.batchNumber}`, content, async () => {}, { wide: true, submitLabel: 'Close' });
    
    // Inject the print button into the modal footer
    const footer = document.querySelector('.modal-footer');
    footer.insertBefore(printBtn, footer.firstChild);
    footer.querySelector('.btn-secondary:not(.btn-sm)').remove(); // remove default cancel button
  }

  return { render };
})();